name: download-ECoF

# Run at 00:00 UTC every day
on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  download-ECoF:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::janitor

      - name: Download ECoF
        run: Rscript -e 'source("download_ECoF.R")'

      - name: Commit file
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add archive/*
          git commit -m 'Update archive' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
